[package]
name = "zevune-orchard-lab"
version = "0.1.0"
edition = "2021"
rust-version = "1.98.1"
publish = false

[dependencies]
orchard = "=0.15.5"
rand = "=0.8.5"
sha2 = "=0.10.9"
nonempty = "=0.11.0"
incrementalmerkletree = "=0.8.1"
argon2 = { version = "=0.5.3", default-features = false, features = ["alloc", "zeroize"] }
chacha20poly1305 = "=0.10.1"
zeroize = "=1.9.0"
zip32 = "=0.2.1"

[features]
local-funding-lab = []

[[bin]]
name = "zevune-funded-scenario"
path = "src/bin/zevune-funded-scenario.rs"
required-features = ["local-funding-lab"]

[[bin]]
name = "zevune-wallet-local"
path = "src/bin/zevune-wallet-local.rs"
required-features = ["local-funding-lab"]

[workspace]

[profile.release]
opt-level = 3
